package com.websitethoitrang.entities;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mathang generated by hbm2java
 */
@Entity
@Table(name = "mathang", catalog = "thoitrang")
public class Mathang implements java.io.Serializable {

	private String mamh;
	private Chatlieu chatlieu;
	private Loaikh loaikh;
	private Loaimh loaimh;
	private Nhanhieu nhanhieu;
	private String tenmh;
	private String mota;
	private int trangthai;
	private Integer cachlam;
	private Set<Ctpx> ctpxes = new HashSet<Ctpx>(0);
	private Set<Hinhanhmh> hinhanhmhs = new HashSet<Hinhanhmh>(0);
	private Set<Banggia> banggias = new HashSet<Banggia>(0);
	private Set<Ctpn> ctpns = new HashSet<Ctpn>(0);
	private Set<Cthd> cthds = new HashSet<Cthd>(0);
	private Set<Ctddh> ctddhs = new HashSet<Ctddh>(0);
	private Set<Ctdkm> ctdkms = new HashSet<Ctdkm>(0);
	private Set<Ctpd> ctpds = new HashSet<Ctpd>(0);
	private Set<KhoMhSize> khoMhSizes = new HashSet<KhoMhSize>(0);
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);

	public Mathang() {
	}

	public Mathang(String mamh, Nhanhieu nhanhieu, String tenmh, String mota, int trangthai) {
		this.mamh = mamh;
		this.nhanhieu = nhanhieu;
		this.tenmh = tenmh;
		this.mota = mota;
		this.trangthai = trangthai;
	}

	public Mathang(String mamh, Chatlieu chatlieu, Loaikh loaikh, Loaimh loaimh, Nhanhieu nhanhieu, String tenmh,
			String mota, int trangthai, Integer cachlam, Set<Ctpx> ctpxes, Set<Hinhanhmh> hinhanhmhs,
			Set<Banggia> banggias, Set<Ctpn> ctpns, Set<Cthd> cthds, Set<Ctddh> ctddhs, Set<Ctdkm> ctdkms,
			Set<Ctpd> ctpds, Set<KhoMhSize> khoMhSizes, Set<Danhgia> danhgias) {
		this.mamh = mamh;
		this.chatlieu = chatlieu;
		this.loaikh = loaikh;
		this.loaimh = loaimh;
		this.nhanhieu = nhanhieu;
		this.tenmh = tenmh;
		this.mota = mota;
		this.trangthai = trangthai;
		this.cachlam = cachlam;
		this.ctpxes = ctpxes;
		this.hinhanhmhs = hinhanhmhs;
		this.banggias = banggias;
		this.ctpns = ctpns;
		this.cthds = cthds;
		this.ctddhs = ctddhs;
		this.ctdkms = ctdkms;
		this.ctpds = ctpds;
		this.khoMhSizes = khoMhSizes;
		this.danhgias = danhgias;
	}

	@Id

	@Column(name = "MAMH", unique = true, nullable = false, length = 10)
	public String getMamh() {
		return this.mamh;
	}

	public void setMamh(String mamh) {
		this.mamh = mamh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACL")
	public Chatlieu getChatlieu() {
		return this.chatlieu;
	}

	public void setChatlieu(Chatlieu chatlieu) {
		this.chatlieu = chatlieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MALOAIKH")
	public Loaikh getLoaikh() {
		return this.loaikh;
	}

	public void setLoaikh(Loaikh loaikh) {
		this.loaikh = loaikh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MALOAIMH")
	public Loaimh getLoaimh() {
		return this.loaimh;
	}

	public void setLoaimh(Loaimh loaimh) {
		this.loaimh = loaimh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANH", nullable = false)
	public Nhanhieu getNhanhieu() {
		return this.nhanhieu;
	}

	public void setNhanhieu(Nhanhieu nhanhieu) {
		this.nhanhieu = nhanhieu;
	}

	@Column(name = "TENMH", nullable = false, length = 500)
	public String getTenmh() {
		return this.tenmh;
	}

	public void setTenmh(String tenmh) {
		this.tenmh = tenmh;
	}

	@Column(name = "MOTA", nullable = false, length = 500)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "TRANGTHAI", nullable = false)
	public int getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(int trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "CACHLAM")
	public Integer getCachlam() {
		return this.cachlam;
	}

	public void setCachlam(Integer cachlam) {
		this.cachlam = cachlam;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctpx> getCtpxes() {
		return this.ctpxes;
	}

	public void setCtpxes(Set<Ctpx> ctpxes) {
		this.ctpxes = ctpxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Hinhanhmh> getHinhanhmhs() {
		return this.hinhanhmhs;
	}

	public void setHinhanhmhs(Set<Hinhanhmh> hinhanhmhs) {
		this.hinhanhmhs = hinhanhmhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Banggia> getBanggias() {
		return this.banggias;
	}

	public void setBanggias(Set<Banggia> banggias) {
		this.banggias = banggias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctpn> getCtpns() {
		return this.ctpns;
	}

	public void setCtpns(Set<Ctpn> ctpns) {
		this.ctpns = ctpns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Cthd> getCthds() {
		return this.cthds;
	}

	public void setCthds(Set<Cthd> cthds) {
		this.cthds = cthds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctddh> getCtddhs() {
		return this.ctddhs;
	}

	public void setCtddhs(Set<Ctddh> ctddhs) {
		this.ctddhs = ctddhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctdkm> getCtdkms() {
		return this.ctdkms;
	}

	public void setCtdkms(Set<Ctdkm> ctdkms) {
		this.ctdkms = ctdkms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctpd> getCtpds() {
		return this.ctpds;
	}

	public void setCtpds(Set<Ctpd> ctpds) {
		this.ctpds = ctpds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<KhoMhSize> getKhoMhSizes() {
		return this.khoMhSizes;
	}

	public void setKhoMhSizes(Set<KhoMhSize> khoMhSizes) {
		this.khoMhSizes = khoMhSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

}
