package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BanggiaId generated by hbm2java
 */
@Embeddable
public class BanggiaId implements java.io.Serializable {

	private String mamh;
	private String manv;
	private Date ngayapdung;

	public BanggiaId() {
	}

	public BanggiaId(String mamh, String manv, Date ngayapdung) {
		this.mamh = mamh;
		this.manv = manv;
		this.ngayapdung = ngayapdung;
	}

	@Column(name = "MAMH", nullable = false, length = 10)
	public String getMamh() {
		return this.mamh;
	}

	public void setMamh(String mamh) {
		this.mamh = mamh;
	}

	@Column(name = "MANV", nullable = false, length = 10)
	public String getManv() {
		return this.manv;
	}

	public void setManv(String manv) {
		this.manv = manv;
	}

	@Column(name = "NGAYAPDUNG", nullable = false, length = 10)
	public Date getNgayapdung() {
		return this.ngayapdung;
	}

	public void setNgayapdung(Date ngayapdung) {
		this.ngayapdung = ngayapdung;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BanggiaId))
			return false;
		BanggiaId castOther = (BanggiaId) other;

		return ((this.getMamh() == castOther.getMamh()) || (this.getMamh() != null && castOther.getMamh() != null
				&& this.getMamh().equals(castOther.getMamh())))
				&& ((this.getManv() == castOther.getManv()) || (this.getManv() != null && castOther.getManv() != null
						&& this.getManv().equals(castOther.getManv())))
				&& ((this.getNgayapdung() == castOther.getNgayapdung())
						|| (this.getNgayapdung() != null && castOther.getNgayapdung() != null
								&& this.getNgayapdung().equals(castOther.getNgayapdung())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMamh() == null ? 0 : this.getMamh().hashCode());
		result = 37 * result + (getManv() == null ? 0 : this.getManv().hashCode());
		result = 37 * result + (getNgayapdung() == null ? 0 : this.getNgayapdung().hashCode());
		return result;
	}

}
