package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Chatlieu generated by hbm2java
 */
@Entity
@Table(name = "chatlieu", catalog = "thoitrang", uniqueConstraints = @UniqueConstraint(columnNames = "TENVAI"))
public class Chatlieu implements java.io.Serializable {

	private String macl;
	private String tenvai;
	private Set<Mathang> mathangs = new HashSet<Mathang>(0);

	public Chatlieu() {
	}

	public Chatlieu(String macl, String tenvai) {
		this.macl = macl;
		this.tenvai = tenvai;
	}

	public Chatlieu(String macl, String tenvai, Set<Mathang> mathangs) {
		this.macl = macl;
		this.tenvai = tenvai;
		this.mathangs = mathangs;
	}

	@Id

	@Column(name = "MACL", unique = true, nullable = false, length = 10)
	public String getMacl() {
		return this.macl;
	}

	public void setMacl(String macl) {
		this.macl = macl;
	}

	@Column(name = "TENVAI", unique = true, nullable = false, length = 20)
	public String getTenvai() {
		return this.tenvai;
	}

	public void setTenvai(String tenvai) {
		this.tenvai = tenvai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chatlieu")
	public Set<Mathang> getMathangs() {
		return this.mathangs;
	}

	public void setMathangs(Set<Mathang> mathangs) {
		this.mathangs = mathangs;
	}

}
