package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Chinhanh generated by hbm2java
 */
@Entity
@Table(name = "chinhanh", catalog = "thoitrang", uniqueConstraints = @UniqueConstraint(columnNames = "TENCN"))
public class Chinhanh implements java.io.Serializable {

	private String macn;
	private String tencn;
	private Set<Phieuxuat> phieuxuats = new HashSet<Phieuxuat>(0);

	public Chinhanh() {
	}

	public Chinhanh(String macn, String tencn) {
		this.macn = macn;
		this.tencn = tencn;
	}

	public Chinhanh(String macn, String tencn, Set<Phieuxuat> phieuxuats) {
		this.macn = macn;
		this.tencn = tencn;
		this.phieuxuats = phieuxuats;
	}

	@Id

	@Column(name = "MACN", unique = true, nullable = false, length = 10)
	public String getMacn() {
		return this.macn;
	}

	public void setMacn(String macn) {
		this.macn = macn;
	}

	@Column(name = "TENCN", unique = true, nullable = false, length = 50)
	public String getTencn() {
		return this.tencn;
	}

	public void setTencn(String tencn) {
		this.tencn = tencn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chinhanh")
	public Set<Phieuxuat> getPhieuxuats() {
		return this.phieuxuats;
	}

	public void setPhieuxuats(Set<Phieuxuat> phieuxuats) {
		this.phieuxuats = phieuxuats;
	}

}
