package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ctdkm generated by hbm2java
 */
@Entity
@Table(name = "ctdkm", catalog = "thoitrang")
public class Ctdkm implements java.io.Serializable {

	private CtdkmId id;
	private Dotkhuyenmai dotkhuyenmai;
	private Mathang mathang;
	private double mucgiamgia;

	public Ctdkm() {
	}

	public Ctdkm(CtdkmId id, Dotkhuyenmai dotkhuyenmai, Mathang mathang, double mucgiamgia) {
		this.id = id;
		this.dotkhuyenmai = dotkhuyenmai;
		this.mathang = mathang;
		this.mucgiamgia = mucgiamgia;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "madkm", column = @Column(name = "MADKM", nullable = false, length = 10)),
			@AttributeOverride(name = "mamh", column = @Column(name = "MAMH", nullable = false, length = 10)) })
	public CtdkmId getId() {
		return this.id;
	}

	public void setId(CtdkmId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MADKM", nullable = false, insertable = false, updatable = false)
	public Dotkhuyenmai getDotkhuyenmai() {
		return this.dotkhuyenmai;
	}

	public void setDotkhuyenmai(Dotkhuyenmai dotkhuyenmai) {
		this.dotkhuyenmai = dotkhuyenmai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAMH", nullable = false, insertable = false, updatable = false)
	public Mathang getMathang() {
		return this.mathang;
	}

	public void setMathang(Mathang mathang) {
		this.mathang = mathang;
	}

	@Column(name = "MUCGIAMGIA", nullable = false, precision = 22, scale = 0)
	public double getMucgiamgia() {
		return this.mucgiamgia;
	}

	public void setMucgiamgia(double mucgiamgia) {
		this.mucgiamgia = mucgiamgia;
	}

}
