package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtdkmId generated by hbm2java
 */
@Embeddable
public class CtdkmId implements java.io.Serializable {

	private String madkm;
	private String mamh;

	public CtdkmId() {
	}

	public CtdkmId(String madkm, String mamh) {
		this.madkm = madkm;
		this.mamh = mamh;
	}

	@Column(name = "MADKM", nullable = false, length = 10)
	public String getMadkm() {
		return this.madkm;
	}

	public void setMadkm(String madkm) {
		this.madkm = madkm;
	}

	@Column(name = "MAMH", nullable = false, length = 10)
	public String getMamh() {
		return this.mamh;
	}

	public void setMamh(String mamh) {
		this.mamh = mamh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtdkmId))
			return false;
		CtdkmId castOther = (CtdkmId) other;

		return ((this.getMadkm() == castOther.getMadkm()) || (this.getMadkm() != null && castOther.getMadkm() != null
				&& this.getMadkm().equals(castOther.getMadkm())))
				&& ((this.getMamh() == castOther.getMamh()) || (this.getMamh() != null && castOther.getMamh() != null
						&& this.getMamh().equals(castOther.getMamh())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMadkm() == null ? 0 : this.getMadkm().hashCode());
		result = 37 * result + (getMamh() == null ? 0 : this.getMamh().hashCode());
		return result;
	}

}
