package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CthdId generated by hbm2java
 */
@Embeddable
public class CthdId implements java.io.Serializable {

	private String sohd;
	private String mamh;

	public CthdId() {
	}

	public CthdId(String sohd, String mamh) {
		this.sohd = sohd;
		this.mamh = mamh;
	}

	@Column(name = "SOHD", nullable = false, length = 10)
	public String getSohd() {
		return this.sohd;
	}

	public void setSohd(String sohd) {
		this.sohd = sohd;
	}

	@Column(name = "MAMH", nullable = false, length = 10)
	public String getMamh() {
		return this.mamh;
	}

	public void setMamh(String mamh) {
		this.mamh = mamh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CthdId))
			return false;
		CthdId castOther = (CthdId) other;

		return ((this.getSohd() == castOther.getSohd()) || (this.getSohd() != null && castOther.getSohd() != null
				&& this.getSohd().equals(castOther.getSohd())))
				&& ((this.getMamh() == castOther.getMamh()) || (this.getMamh() != null && castOther.getMamh() != null
						&& this.getMamh().equals(castOther.getMamh())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSohd() == null ? 0 : this.getSohd().hashCode());
		result = 37 * result + (getMamh() == null ? 0 : this.getMamh().hashCode());
		return result;
	}

}
