package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ctpx generated by hbm2java
 */
@Entity
@Table(name = "ctpx", catalog = "thoitrang")
public class Ctpx implements java.io.Serializable {

	private CtpxId id;
	private Mathang mathang;
	private Phieuxuat phieuxuat;
	private int soluong;

	public Ctpx() {
	}

	public Ctpx(CtpxId id, Mathang mathang, Phieuxuat phieuxuat, int soluong) {
		this.id = id;
		this.mathang = mathang;
		this.phieuxuat = phieuxuat;
		this.soluong = soluong;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "mapx", column = @Column(name = "MAPX", nullable = false, length = 10)),
			@AttributeOverride(name = "mamh", column = @Column(name = "MAMH", nullable = false, length = 10)) })
	public CtpxId getId() {
		return this.id;
	}

	public void setId(CtpxId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAMH", nullable = false, insertable = false, updatable = false)
	public Mathang getMathang() {
		return this.mathang;
	}

	public void setMathang(Mathang mathang) {
		this.mathang = mathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAPX", nullable = false, insertable = false, updatable = false)
	public Phieuxuat getPhieuxuat() {
		return this.phieuxuat;
	}

	public void setPhieuxuat(Phieuxuat phieuxuat) {
		this.phieuxuat = phieuxuat;
	}

	@Column(name = "SOLUONG", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

}
