package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DanhgiaId generated by hbm2java
 */
@Embeddable
public class DanhgiaId implements java.io.Serializable {

	private String tentk;
	private String mamh;

	public DanhgiaId() {
	}

	public DanhgiaId(String tentk, String mamh) {
		this.tentk = tentk;
		this.mamh = mamh;
	}

	@Column(name = "TENTK", nullable = false, length = 50)
	public String getTentk() {
		return this.tentk;
	}

	public void setTentk(String tentk) {
		this.tentk = tentk;
	}

	@Column(name = "MAMH", nullable = false, length = 10)
	public String getMamh() {
		return this.mamh;
	}

	public void setMamh(String mamh) {
		this.mamh = mamh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DanhgiaId))
			return false;
		DanhgiaId castOther = (DanhgiaId) other;

		return ((this.getTentk() == castOther.getTentk()) || (this.getTentk() != null && castOther.getTentk() != null
				&& this.getTentk().equals(castOther.getTentk())))
				&& ((this.getMamh() == castOther.getMamh()) || (this.getMamh() != null && castOther.getMamh() != null
						&& this.getMamh().equals(castOther.getMamh())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTentk() == null ? 0 : this.getTentk().hashCode());
		result = 37 * result + (getMamh() == null ? 0 : this.getMamh().hashCode());
		return result;
	}

}
