package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kho generated by hbm2java
 */
@Entity
@Table(name = "kho", catalog = "thoitrang")
public class Kho implements java.io.Serializable {

	private String makho;
	private String tenkho;
	private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);
	private Set<Phieuxuat> phieuxuats = new HashSet<Phieuxuat>(0);
	private Set<KhoMhSize> khoMhSizes = new HashSet<KhoMhSize>(0);

	public Kho() {
	}

	public Kho(String makho, String tenkho) {
		this.makho = makho;
		this.tenkho = tenkho;
	}

	public Kho(String makho, String tenkho, Set<Phieunhap> phieunhaps, Set<Phieuxuat> phieuxuats,
			Set<KhoMhSize> khoMhSizes) {
		this.makho = makho;
		this.tenkho = tenkho;
		this.phieunhaps = phieunhaps;
		this.phieuxuats = phieuxuats;
		this.khoMhSizes = khoMhSizes;
	}

	@Id

	@Column(name = "MAKHO", unique = true, nullable = false, length = 10)
	public String getMakho() {
		return this.makho;
	}

	public void setMakho(String makho) {
		this.makho = makho;
	}

	@Column(name = "TENKHO", nullable = false, length = 50)
	public String getTenkho() {
		return this.tenkho;
	}

	public void setTenkho(String tenkho) {
		this.tenkho = tenkho;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kho")
	public Set<Phieunhap> getPhieunhaps() {
		return this.phieunhaps;
	}

	public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
		this.phieunhaps = phieunhaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kho")
	public Set<Phieuxuat> getPhieuxuats() {
		return this.phieuxuats;
	}

	public void setPhieuxuats(Set<Phieuxuat> phieuxuats) {
		this.phieuxuats = phieuxuats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kho")
	public Set<KhoMhSize> getKhoMhSizes() {
		return this.khoMhSizes;
	}

	public void setKhoMhSizes(Set<KhoMhSize> khoMhSizes) {
		this.khoMhSizes = khoMhSizes;
	}

}
