package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KhoMhSize generated by hbm2java
 */
@Entity
@Table(name = "kho_mh_size", catalog = "thoitrang")
public class KhoMhSize implements java.io.Serializable {

	private KhoMhSizeId id;
	private Kho kho;
	private Mathang mathang;
	private Size size;
	private int soluongton;

	public KhoMhSize() {
	}

	public KhoMhSize(KhoMhSizeId id, Kho kho, Mathang mathang, Size size, int soluongton) {
		this.id = id;
		this.kho = kho;
		this.mathang = mathang;
		this.size = size;
		this.soluongton = soluongton;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "makho", column = @Column(name = "MAKHO", nullable = false, length = 10)),
			@AttributeOverride(name = "mamh", column = @Column(name = "MAMH", nullable = false, length = 10)),
			@AttributeOverride(name = "masize", column = @Column(name = "MASIZE", nullable = false)) })
	public KhoMhSizeId getId() {
		return this.id;
	}

	public void setId(KhoMhSizeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKHO", nullable = false, insertable = false, updatable = false)
	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAMH", nullable = false, insertable = false, updatable = false)
	public Mathang getMathang() {
		return this.mathang;
	}

	public void setMathang(Mathang mathang) {
		this.mathang = mathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASIZE", nullable = false, insertable = false, updatable = false)
	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	@Column(name = "SOLUONGTON", nullable = false)
	public int getSoluongton() {
		return this.soluongton;
	}

	public void setSoluongton(int soluongton) {
		this.soluongton = soluongton;
	}

}
