package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaikh generated by hbm2java
 */
@Entity
@Table(name = "loaikh", catalog = "thoitrang")
public class Loaikh implements java.io.Serializable {

	private int maloaikh;
	private String tenloaikh;
	private Set<Mathang> mathangs = new HashSet<Mathang>(0);

	public Loaikh() {
	}

	public Loaikh(int maloaikh, String tenloaikh) {
		this.maloaikh = maloaikh;
		this.tenloaikh = tenloaikh;
	}

	public Loaikh(int maloaikh, String tenloaikh, Set<Mathang> mathangs) {
		this.maloaikh = maloaikh;
		this.tenloaikh = tenloaikh;
		this.mathangs = mathangs;
	}

	@Id

	@Column(name = "MALOAIKH", unique = true, nullable = false)
	public int getMaloaikh() {
		return this.maloaikh;
	}

	public void setMaloaikh(int maloaikh) {
		this.maloaikh = maloaikh;
	}

	@Column(name = "TENLOAIKH", nullable = false, length = 10)
	public String getTenloaikh() {
		return this.tenloaikh;
	}

	public void setTenloaikh(String tenloaikh) {
		this.tenloaikh = tenloaikh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaikh")
	public Set<Mathang> getMathangs() {
		return this.mathangs;
	}

	public void setMathangs(Set<Mathang> mathangs) {
		this.mathangs = mathangs;
	}

}
