package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieunhap generated by hbm2java
 */
@Entity
@Table(name = "phieunhap", catalog = "thoitrang")
public class Phieunhap implements java.io.Serializable {

	private String mapn;
	private Dondathang dondathang;
	private Kho kho;
	private Nhanvien nhanvien;
	private Date ngaynhap;
	private Set<Ctpn> ctpns = new HashSet<Ctpn>(0);

	public Phieunhap() {
	}

	public Phieunhap(String mapn, Dondathang dondathang, Kho kho, Nhanvien nhanvien) {
		this.mapn = mapn;
		this.dondathang = dondathang;
		this.kho = kho;
		this.nhanvien = nhanvien;
	}

	public Phieunhap(String mapn, Dondathang dondathang, Kho kho, Nhanvien nhanvien, Date ngaynhap, Set<Ctpn> ctpns) {
		this.mapn = mapn;
		this.dondathang = dondathang;
		this.kho = kho;
		this.nhanvien = nhanvien;
		this.ngaynhap = ngaynhap;
		this.ctpns = ctpns;
	}

	@Id

	@Column(name = "MAPN", unique = true, nullable = false, length = 10)
	public String getMapn() {
		return this.mapn;
	}

	public void setMapn(String mapn) {
		this.mapn = mapn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MADDH", nullable = false)
	public Dondathang getDondathang() {
		return this.dondathang;
	}

	public void setDondathang(Dondathang dondathang) {
		this.dondathang = dondathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKHO", nullable = false)
	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANV", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYNHAP", length = 10)
	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieunhap")
	public Set<Ctpn> getCtpns() {
		return this.ctpns;
	}

	public void setCtpns(Set<Ctpn> ctpns) {
		this.ctpns = ctpns;
	}

}
