package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieuxuat generated by hbm2java
 */
@Entity
@Table(name = "phieuxuat", catalog = "thoitrang")
public class Phieuxuat implements java.io.Serializable {

	private String mapx;
	private Chinhanh chinhanh;
	private Kho kho;
	private Nhanvien nhanvien;
	private Date ngayxuat;
	private Set<Ctpx> ctpxes = new HashSet<Ctpx>(0);

	public Phieuxuat() {
	}

	public Phieuxuat(String mapx, Chinhanh chinhanh, Kho kho, Nhanvien nhanvien) {
		this.mapx = mapx;
		this.chinhanh = chinhanh;
		this.kho = kho;
		this.nhanvien = nhanvien;
	}

	public Phieuxuat(String mapx, Chinhanh chinhanh, Kho kho, Nhanvien nhanvien, Date ngayxuat, Set<Ctpx> ctpxes) {
		this.mapx = mapx;
		this.chinhanh = chinhanh;
		this.kho = kho;
		this.nhanvien = nhanvien;
		this.ngayxuat = ngayxuat;
		this.ctpxes = ctpxes;
	}

	@Id

	@Column(name = "MAPX", unique = true, nullable = false, length = 10)
	public String getMapx() {
		return this.mapx;
	}

	public void setMapx(String mapx) {
		this.mapx = mapx;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACN", nullable = false)
	public Chinhanh getChinhanh() {
		return this.chinhanh;
	}

	public void setChinhanh(Chinhanh chinhanh) {
		this.chinhanh = chinhanh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKHO", nullable = false)
	public Kho getKho() {
		return this.kho;
	}

	public void setKho(Kho kho) {
		this.kho = kho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANV", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYXUAT", length = 10)
	public Date getNgayxuat() {
		return this.ngayxuat;
	}

	public void setNgayxuat(Date ngayxuat) {
		this.ngayxuat = ngayxuat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieuxuat")
	public Set<Ctpx> getCtpxes() {
		return this.ctpxes;
	}

	public void setCtpxes(Set<Ctpx> ctpxes) {
		this.ctpxes = ctpxes;
	}

}
