package com.example.demo4.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Size generated by hbm2java
 */
@Entity
@Table(name = "size", catalog = "thoitrang")
public class Size implements java.io.Serializable {

	private int masize;
	private String tensize;
	private Set<KhoMhSize> khoMhSizes = new HashSet<KhoMhSize>(0);

	public Size() {
	}

	public Size(int masize, String tensize) {
		this.masize = masize;
		this.tensize = tensize;
	}

	public Size(int masize, String tensize, Set<KhoMhSize> khoMhSizes) {
		this.masize = masize;
		this.tensize = tensize;
		this.khoMhSizes = khoMhSizes;
	}

	@Id

	@Column(name = "MASIZE", unique = true, nullable = false)
	public int getMasize() {
		return this.masize;
	}

	public void setMasize(int masize) {
		this.masize = masize;
	}

	@Column(name = "TENSIZE", nullable = false, length = 5)
	public String getTensize() {
		return this.tensize;
	}

	public void setTensize(String tensize) {
		this.tensize = tensize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "size")
	public Set<KhoMhSize> getKhoMhSizes() {
		return this.khoMhSizes;
	}

	public void setKhoMhSizes(Set<KhoMhSize> khoMhSizes) {
		this.khoMhSizes = khoMhSizes;
	}

}
